version: '2.4'
services:
  dev:
    image: gfw/api-settings
    build:
      context: .
      target: development
    env_file: ./dev/env
    volumes:
      - "./src:/opt/project/src"
      - "./spec:/opt/project/spec"
      - "./package.json:/opt/project/package.json"
      - "./dev:/opt/project/dev"
      - "~/.config/gcloud:/root/.config/gcloud"
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - NODE_ENV=development

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3000:8080"
    environment:
      - URL=http://localhost:8080/openapi.json
